name: Decompress and Serve Release

on:
  release:
    types:
      - created

jobs:
  decompress-and-serve:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get External IP
      id: get-ip
      run: echo "::set-output name=IP::$(curl -s ifconfig.me)"

    - name: Ask for Release Name and Parts
      id: prompt
      run: |
        echo "Enter the release name (e.g., v1.0.0):"
        read release_name
        echo "Enter the number of parts (assuming each part is 2GB):"
        read num_parts
        echo "::set-output name=RELEASE_NAME::$release_name"
        echo "::set-output name=NUM_PARTS::$num_parts"

    - name: Download and Decompress Release
      run: |
        release_name=${{ steps.prompt.outputs.RELEASE_NAME }}
        num_parts=${{ steps.prompt.outputs.NUM_PARTS }}
        
        # Download and decompress each part
        for ((part=1; part<=$num_parts; part++)); do
          wget "https://github.com/${{ github.repository }}/releases/download/$release_name/${release_name}_part${part}.zip"
          unzip "${release_name}_part${part}.zip" -d "decompressed_files"
        done

    - name: Start HTTP Server
      run: |
        cd decompressed_files
        python3 -m http.server 8000
      background: true

    - name: Wait for Server to Start
      run: sleep 5

    - name: Display Server URL
      run: |
        echo "Server is running at http://${{ steps.get-ip.outputs.IP }}:8000/"
        echo "Release Name: ${{ steps.prompt.outputs.RELEASE_NAME }}"
        echo "Number of Parts: ${{ steps.prompt.outputs.NUM_PARTS }}"
